plugins {
    id 'net.neoforged.gradle' version '7.0.80'
    id 'net.neoforged.gradle.userdev' version '7.0.80'
    id 'eclipse'
    id 'maven-publish'
}

version = '1.0.0'
group = 'com.imaginarium.createplayerfilter'
archivesBaseName = 'createplayerfilter'

java {
    toolchain.languageVersion = JavaLanguageVersion.of(21)
}

minecraft {
    version = '1.21.1'
}

repositories {
    mavenLocal()
    maven { url = 'https://repo.neoforged.net/releases' }
    maven { url = 'https://maven.blamejared.com' }
    maven { url = 'https://maven.theillusivec4.com/' }
}

dependencies {
    minecraft "net.neoforged:forge:1.21.1-52.0.21"
    
    // Create Mod
    compileOnly "com.simibubi.create:create-neoforge:0.5.1.o+mc1.21.1"
    runtimeOnly "com.simibubi.create:create-neoforge:0.5.1.o+mc1.21.1"
}

tasks.named('jar', Jar) {
    manifest {
        attributes(
                "Specification-Title": "Create Player Filter",
                "Specification-Vendor": "Imaginarium",
                "Specification-Version": "1",
                "Implementation-Title": project.name,
                "Implementation-Version": "${version}",
                "Implementation-Vendor": "Imaginarium",
                "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
        )
    }
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            artifact jar {
                builtBy reobfJar
            }
        }
    }
    repositories {
        maven {
            name = "local"
            url = "file://" + System.getenv("MAVEN_LOCAL") ?: layout.buildDirectory.dir("repo")
        }
    }
}
